In [18]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt

In [19]:
df=pd.read_csv("Book2.csv")
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5727  Subject: re : research and development charges...     0
5728  Subject: re : receipts from visit  jim ,  than...     0
5729  Subject: re : enron case study update  wow ! a...     0
5730  Subject: re : interest  david ,  please , call...     0
5731  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5732 rows x 2 columns]

# Columns drop====

In [20]:
#Dropping columns between a range ================

#df.drop(df.iloc[:, 2:110], inplace = True, axis = 1)
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5727  Subject: re : research and development charges...     0
5728  Subject: re : receipts from visit  jim ,  than...     0
5729  Subject: re : enron case study update  wow ! a...     0
5730  Subject: re : interest  david ,  please , call...     0
5731  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5732 rows x 2 columns]

In [21]:
df.dropna(axis = 0, how ='any')
df.dropna(how='all', axis=0)
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5727  Subject: re : research and development charges...     0
5728  Subject: re : receipts from visit  jim ,  than...     0
5729  Subject: re : enron case study update  wow ! a...     0
5730  Subject: re : interest  david ,  please , call...     0
5731  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5732 rows x 2 columns]

In [22]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [23]:
x=df.text.values



In [24]:
y=df.spam.values
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [25]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=10)

# Using Counter-Vectorizer (TFidf Vectorizer) == for converting text to int64

In [26]:
#from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
#cv=CountVectorizer()
cv=TfidfVectorizer()

In [27]:
# x_train=cv.fit_transform(xtrain)
# x_train.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
#for k-fold

In [33]:
x_train=cv.fit_transform(x)
x_train.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.11413074, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

# Now Using ML Algorithm As Naive Bayes ==> Multinomial NB library 

In [28]:
from sklearn.naive_bayes import MultinomialNB
mnb=MultinomialNB(alpha=0.1)
mnb.fit(x_train,ytrain)


MultinomialNB(alpha=0.1)

In [29]:
x_test=cv.fit_transform(xtest)
x_test.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [30]:
mnb.score(x_train,ytrain)

0.9995637949836423

# K-fold corss validation

In [34]:
from sklearn.model_selection import cross_val_score
cvs=cross_val_score(mnb,x_train,y,cv=10)

In [36]:
cvs

array([0.98954704, 0.98780488, 0.9947644 , 0.991274  , 0.9947644 ,
       0.9895288 , 0.991274  , 0.991274  , 0.9895288 , 0.991274  ])

In [37]:
cvs.mean()

0.9911034289849254